web:
    image: touchcast/docker-nginx-php7
    ports:
        - "80:80"
    volumes:
        - ./app:/var/www/html
    links:
     - db:db_container
db:
    image: mysql
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_USER: user
        MYSQL_PASSWORD: password
        MYSQL_DATABASE: project_db